# Custom Language File for Launcher Customizer

[ejs.app]
title = "Paco Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.twitch.tv/pacohontaz"
mediaTwitterURL = "https://twitter.com/pacohontaz"
mediaInstagramURL = "https://www.instagram.com/pacohontaz/"
mediaYouTubeURL = "https://www.youtube.com/@Pacohontaz"
mediaDiscordURL = "https://discord.gg/g2fqGNU8T4"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Wilkommen im Paco Minecraft Launcher"
welcomeDescription = "Bei Paco werden alle schwach, weil sein Aussehen sie anzieht und sein Charakter wieder aus // Grantige_Gabi: ich finde deine streams sind wie eine sternschnuppe, du machst das wünsche wahr werden."
welcomeDescCTA = ""
